version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
    versioning-strategy: increase-if-necessary
    groups:
      prod-deps:
        dependency-type: "production"
      dev-deps:
        dependency-type: "development"

  # Enable version updates for GitHub Actions workflows
  - package-ecosystem: "github-actions"
    # Look for workflow files in the `.github/workflows` directory
    directory: ".github/workflows"
    # Check the GitHub Actions API for updates every day (weekdays)
    schedule:
      interval: "weekly"
